import express from "express";
import generarIdMiddleware from "../middleware/generarIdMiddleware.js";
import { getAll, getById, createOne, updateOne, deleteOne,getAllExcel } from "../controllers/alumno_extracurricularController.js";
const router = express.Router();
router.get("/", getAll);
router.get("/excel/:sid_instituto", getAllExcel);
router.get("/:id", getById);
// router.post("/", createOne);
router.post("/", generarIdMiddleware, createOne);
router.put("/:id", updateOne);
router.delete("/:id", deleteOne);
export const basePath = "/api/alumno_extracurricular";
export default router;