import express from "express";
import { getAll, getById, createOne, updateOne, deleteOne, acceptSchool } from "../controllers/escuelas_registradasController.js";
const router = express.Router();
router.get("/", getAll);
router.get("/:id", getById);
router.post("/", createOne);
router.post("/:id/aceptar", acceptSchool);
router.put("/:id", updateOne);
router.delete("/:id", deleteOne);
export const basePath = "/api/escuelas_registradas";
export default router;
