import express from "express";
import { getAll, getById, createOne, updateOne, deleteOne } from "../controllers/rolController.js";
const router = express.Router();
router.get("/", getAll);
router.get("/:id", getById);
router.post("/", createOne);
router.put("/:id", updateOne);
router.delete("/:id", deleteOne);
export const basePath = "/api/rol";
export default router;